// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chektkdrwycfenlabpqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoZWt0a2Ryd3ljZmVubGFicHFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY3OTM1MzcsImV4cCI6MjA1MjM2OTUzN30.TkOBfK1Ke_pEN9uP6Vtf_PqhEQUMyt3CAmJdiveP38A";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);